### PR TITLE
Fix CSAI-2103 run SonarQube only once

### PR DESCRIPTION
**Pull request by diasdm**
In order to run SonarQube only once:
1. Create a separate job
2. Move mobtest and SonarQube

### CODE REVIEW

**Comment by diasdm** [comment]
Tested here: https://github.com/MOV-AI/movai_DELETE_ME_DAVID/pull/1

**Review by rodrigo-fittipaldi — COMMENTED** [review]
Hi @duartecoelhomovai and @AlexFernandes-MOVAI I believe this was used to SonaQube only. Can you confirm that so @diasdm can change it in the sections that Sonarqube is not running anymore?
```
    steps:
    - name: Checkout    
      uses: actions/checkout@v2
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0
        submodules: recursive
```

**Comment by duartecoelhomovai** [comment]
> Hi @duartecoelhomovai and @AlexFernandes-MOVAI I believe this was used to SonaQube only. Can you confirm that so @diasdm can change it in the sections that Sonarqube is not running anymore?
> 
> ```
>     steps:
>     - name: Checkout    
>       uses: actions/checkout@v2
>       with:
>         # Disabling shallow clone is recommended for improving relevancy of reporting
>         fetch-depth: 0
>         submodules: recursive
> ```

The checkout is needed in all jobs that will interact with the repository. The "fetch-depth: 0", was what we added for sonarqube.

**Comment by diasdm** [comment]
@duartecoelhomovai the shallow clone is now done everywhere, with exception of where the Sonar is run.

**Comment by diasdm** [comment]
Re-tested after changes:
* https://github.com/MOV-AI/movai_DELETE_ME_DAVID/pull/3
* https://github.com/MOV-AI/movai_DELETE_ME_DAVID/pull/4
  * Deploy: https://github.com/MOV-AI/movai_DELETE_ME_DAVID/actions/runs/2421953206

**Review by AlexFernandes-MOVAI — CHANGES_REQUESTED** [review]
Just questioning the parallelism of Jobs here...

Don't we want to do :
1. Static analysis
2. Build
3. Publish

and in the case the build is needed for test:
1. Static analysis
2. Build
3. Unit test
5. Publish

**Comment by diasdm** [comment]
I agree, possibly even with a few more?

1. Documentation?
2. Static analysis
3. Build
4. Unit test
5. Publish
6. Sonar

But currently, the way it is setup, there is no dependency on the Test step from the Build step. Although we know in the future it will be need. Should we add it now?

**Comment by AlexFernandes-MOVAI** [comment]
> I agree, possibly even with a few more?
> 
> 1. Documentation?
> 2. Static analysis
> 3. Build
> 4. Unit test
> 5. Publish
> 6. Sonar
> 
> But currently, the way it is setup, there is no dependency on the Test step from the Build step. Although we know in the future it will be need. Should we add it now?

Yes,  I think so (example here: https://github.com/MOV-AI/.github/blob/c7476aaefa80ca82761d876d350483835f051470/.github/workflows/multi-py-deb-workflow.yml#L116)


why do you put Sonar on last step ?

**Comment by diasdm** [comment]
Sorry, it makes more sense to come before Publish (but actually should not run when Publishing):
1. Documentation?
2. Static analysis
3. Build
4. Unit test
5. Sonar
6. Publish

I'll add the dependency on Build and the `${{ inputs.release == 'false' }}` so it is not executed when publishing. Agree?

**Comment by diasdm** [comment]
Re-tested https://github.com/MOV-AI/movai_DELETE_ME_DAVID/pull/7

**Review by AlexFernandes-MOVAI — APPROVED** [review]

**Comment by diasdm** [comment]
And with publish: https://github.com/MOV-AI/movai_DELETE_ME_DAVID/actions/runs/2595547555

**Review by duartecoelhomovai — APPROVED** [review]

**Comment by duartecoelhomovai** [comment]
@diasdm you will only want this for ros? Maybe also have it in npm, py and all the other templates

**Comment by diasdm** [comment]
AFAIK the ros-workflow was the only where the multiple runs of Sonar was creating issues. Eventually (hopefully soon) we'll need to do these changes in all workflows. But I was indeed forgetting about it, so I'll merge this PR and re-uniformize the workflows in a different one in the next few days. Do you agree?

**Pull request merged**
