### PR TITLE
add message server logs

### PR DESCRIPTION
**Pull request by Michal-movai**
add message server logs after running

### CODE REVIEW

**Review by diasdm — CHANGES_REQUESTED** [review]
AMT this pipeline is used for 2.3.1 and 2.4.0. Since 2.3.1 does not have a message-server we need to:
```
# message-server    
CONTAINER_ID=$(docker ps -a --format '{{.Names}}' --filter "name=^message-server-.*") || true
docker logs "${CONTAINER_ID}" &> "${CONTAINER_ID}.log" || true
```
This way the commands can fail without affecting the pipeline result

**Comment by Michal-movai** [comment]
I thought we had v1 for 2.3 and v2 for 2.4, didn't we?

**Comment by diasdm** [comment]
> I thought we had v1 for 2.3 and v2 for 2.4, didn't we?

We had them separate, but it was the other way around, now both use v2

**Comment by Michal-movai** [comment]
done

**Review by diasdm — APPROVED** [review]

**Pull request merged**
