### PR TITLE
deleted parameter continue_on_mobtest_error from v2

### PR DESCRIPTION
**Pull request by violetamovai**

### CODE REVIEW

**Comment by duartecoelhomovai** [comment]
When this PR is merged please remove the parameter from project-tugbot, project-tugbot2, project-bowebot and project-hik (the critical ones)

**Comment by diasdm** [comment]
> When this PR is merged please remove the parameter from project-tugbot, project-tugbot2, project-bowebot and project-hik (the critical ones)

We are removing it from there first :+1:

**Review by diasdm — APPROVED** [review]

**Review by diasdm — CHANGES_REQUESTED** [review]
After all we need to look into 2.3.0 too

**Comment by diasdm** [comment]
Can only be merged after https://github.com/MOV-AI/project-tugbot2/pull/15

**Review by diasdm — APPROVED** [review]

**Pull request merged**
