### PR TITLE
fleet validation on dedicated runner with terraform

### PR DESCRIPTION
**Pull request by DenisBorzenkov**

### CODE REVIEW

**Review by AlexFernandes-MOVAI — CHANGES_REQUESTED** [review]
Please provide an example of successful execution

**Comment by AlexFernandes-MOVAI** [comment]
waiting for https://github.com/MOV-AI/ee-project-platform/actions/runs/8972435171 to be green

**Comment by AlexFernandes-MOVAI** [comment]
teardown should also be made on `hel-queuer`

**Review by DenisBorzenkov — COMMENTED** [review]
https://github.com/MOV-AI/ee-project-platform/actions/runs/8972435171

**Review by AlexFernandes-MOVAI — APPROVED** [review]

**Pull request merged**
